name: Android CI

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master,develop ]

jobs:
  unit-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
    - uses: actions/upload-artifact@v3
      with:
       name: testDebugUnitTest
       path: ./app/build/reports/tests/testDebugUnitTest/

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Assemble with Gradle
      run: ./gradlew assembleDebug

    - uses: actions/upload-artifact@v3
      with:
        name: sample-app-debug
        path: ./app/build/outputs/apk/debug/app-debug.apk
